apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxteste-deployment
  labels:
    app: nginxteste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxteste
  template:
    metadata:
      labels:
        app: nginxteste
    spec:
      containers:
      - name: nginxteste
        image: murilopaixao2/nginxteste:0.0.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxteste
spec:
  type: NodePort
  selector:
    app: nginxteste
  ports:
    - protocol: TCP
      port: 2529
      targetPort: 80
